### ISSUE TITLE
token 不会过期自动过期吗

### ISSUE THREAD

**Issue by muzi-jiang** [KyleBing/diary#17]
一整天都还是在线的，感觉token不会自动过期，这个可以设置吗，或者在什么地方改动一下代码能快捷实现的

**Comment by KyleBing** [comment]
我是存在 localStorage 里了，可以改成 sessionStorage 里，就可以关闭窗口后失效了。

**Comment by KyleBing** [comment]
存取都改成 sessionStorage https://github.com/KyleBing/diary/blob/master/src/utility.js#L10
